<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.1.1" />
    <PackageReference Include="MSTest.TestFramework" Version="3.1.1" />
    <PackageReference Include="Nethereum.Hex" Version="4.29.0" />
    <PackageReference Include="Nethereum.JsonRpc.RpcClient" Version="4.29.0" />
    <PackageReference Include="Nethereum.Signer" Version="4.29.0" />
    <PackageReference Include="Nethereum.Util" Version="4.29.0" />
    <PackageReference Include="Nethereum.Web3" Version="4.29.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crypto.Exchanges.Cex\Crypto.Exchanges.Cex.csproj" />
    <ProjectReference Include="..\NetCryptoOptions\NetCryptoOptions.csproj" />
    <ProjectReference Include="..\NetLiquidityPools.Bot\NetLiquidityPools.Bot.csproj" />
    <ProjectReference Include="..\NetLiquidityPools.Factory\NetLiquidityPools.Factory.csproj" />
    <ProjectReference Include="..\NetLiquidityPools.Interface\NetLiquidityPools.Interface.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

</Project>
