<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Nethereum.Hex" Version="4.29.0" />
    <PackageReference Include="Nethereum.JsonRpc.RpcClient" Version="4.29.0" />
    <PackageReference Include="Nethereum.Signer" Version="4.29.0" />
    <PackageReference Include="Nethereum.Util" Version="4.29.0" />
    <PackageReference Include="Nethereum.Web3" Version="4.29.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NetLiquidityPools.Interface\NetLiquidityPools.Interface.csproj" />
  </ItemGroup>

</Project>
